sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^4.5.0
install:
  - npm install
before_script:
  - npm prune
script:
  - npm run test-ci
after_success:
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
