sudo: false
install: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
script:
  - npm run test-ci
after_success:
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
