sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
before_install:
  - npm i -g npm@^4.5.0
before_script:
  - npm prune
script:
  - npm run test-ci
after_success:
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
